### ISSUE TITLE
How do I use the partial shown in the README?

### ISSUE THREAD

**Issue by NetOpWibby** [jaredly/hexo-renderer-handlebars#14]
Following the examples from http://handlebarsjs.com, it seems like `{{#calendarDate}}{{this.date}}{{/calendarDate}}` would work but I get "Invalid date" in the rendered HTML.

**Comment by tcr** [comment]
You probably aren't in need of this answer any more, but `{{calendarDate "January 1, 1991"}}` worked for me.

**Comment by NetOpWibby** [comment]
Haha, yup. Hexo frustrated me so I wrote my own blogging engine. I'll close this issue since it seems you've solved it.
