### ISSUE TITLE
Hexo 3 Compatibility

### ISSUE THREAD

**Issue by edwin-bluekite** [jaredly/hexo-renderer-handlebars#5]
I'm running the render with hexo 3.x and having this issue:
```
ReferenceError: hexo is not defined
    at Object.<anonymous> (/opt/cashpickup.hexo/node_modules/hexo-renderer-handlebars/helpers/date.js:2:17)
```

Do you try the render with hexo 3 version?
Any suggestions?

**Comment by klaronix** [comment]
Seems that hexo 3 does not define 'hexo' as global reference any more. Not sure how to access 'hexo' in version 3...

**Comment by dai-shi** [comment]
Hi, `hexo` is not global any more. You need to do something like

    require('./helpers')(hexo);

and helpers/index.js woud be like

    module.exports = function(hexo) {
      // all existing code in it
    };

and passing `hexo` all around to other helpers.
